-- LEGACY / ARCHIVAL FILE
--
-- Do not execute this file against production.
-- It is the original foundation schema and intentionally does not represent
-- the current ArenaCast production database.
--
-- Current production schema and security rules are maintained as ordered
-- migrations under supabase/migrations/. In particular, this old file used
-- development-only public OCR policies that are no longer acceptable.
--
-- For a fresh environment, apply the migrations instead.
