"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase/client";
import { ObsUrlButton } from "@/components/broadcast/obs-url-button";

export default function DashboardPage() {
  const [email,setEmail]=useState(""); const [workspace,setWorkspace]=useState<any>(null); const [tournaments,setTournaments]=useState<any[]>([]); const [error,setError]=useState("");
  useEffect(()=>{void (async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;setEmail(user.email??"");const {data:m}=await supabase.from("organization_members").select("organization_id,role").eq("user_id",user.id).limit(1).maybeSingle();if(!m){setError("Workspace not found.");return;}const [o,s,t]=await Promise.all([supabase.from("organizations").select("id,name").eq("id",m.organization_id).single(),supabase.from("subscriptions").select("status,expires_at,included_tournaments,addon_tournaments,subscription_plans(name)").eq("organization_id",m.organization_id).maybeSingle(),supabase.from("tournaments").select("id,name,total_matches,quota_exempt").eq("organization_id",m.organization_id).order("created_at",{ascending:false})]);const p=Array.isArray(s.data?.subscription_plans)?s.data?.subscription_plans[0]:s.data?.subscription_plans;setWorkspace({...m,...o.data,...s.data,plan:p?.name??"No membership"});setTournaments(t.data??[]);if(t.error)setError(t.error.message);})();},[]);
  async function logout(){await supabase.auth.signOut();window.location.href="/";}
  const used=tournaments.filter(t=>!t.quota_exempt).length;const quota=(workspace?.included_tournaments??0)+(workspace?.addon_tournaments??0);
  return <main className="saas-shell"><div className="saas-wrap"><nav className="saas-nav"><div><p className="eyebrow">ARENACAST WORKSPACE</p><h1 className="saas-title">{workspace?.name??"Workspace"}</h1><p className="saas-muted">{email} · {workspace?.role}</p></div><div className="saas-actions"><Link className="saas-button" href="/#pricing">Membership</Link><Link className="saas-button" href="/broadcast/themes/">Broadcast themes</Link><Link className="saas-button primary" href="/tournaments/new/">+ New tournament</Link><button className="saas-button" onClick={logout}>Sign out</button></div></nav>{error&&<div className="error-banner">{error}</div>}<section className="saas-grid"><article className="saas-card"><p className="saas-muted">MEMBERSHIP</p><div className="saas-kpi">{workspace?.plan??"Pending"}</div><p className="saas-muted">{workspace?.status??"NOT ACTIVE"}</p></article><article className="saas-card"><p className="saas-muted">TOURNAMENT QUOTA</p><div className="saas-kpi">{used} / {quota}</div><p className="saas-muted">Starter: first activation 5 · renewal 4 · +2 for ₹100</p></article><article className="saas-card"><p className="saas-muted">EXPIRY</p><div className="saas-kpi">{workspace?.expires_at?new Date(workspace.expires_at).toLocaleDateString("en-IN"):"Pending"}</div><p className="saas-muted">Pro and Agency are Coming Soon.</p></article></section><section className="saas-card" style={{marginTop:14}}><h2>Your tournaments</h2><p className="saas-muted">Legacy development tournaments are quota-exempt.</p>{tournaments.map(t=><article className="saas-card" style={{marginTop:10}} key={t.id}><strong>{t.name}</strong><p className="saas-muted">{t.total_matches} matches · {t.quota_exempt?"legacy":"membership quota"}</p><div className="saas-actions"><Link className="saas-button" href={"/broadcast/control/?tournament="+encodeURIComponent(t.id)}>Broadcast</Link><ObsUrlButton tournamentId={t.id} /></div></article>)}</section></div></main>;
}
